### ISSUE TITLE
make resource directory configurable 

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#10]
The resource directory seems to be hard coded to : `${basedir}\src\main\wix-resource`

Please make configurable

**Comment by GregDomjan** [comment]
It is configurable, see `resourceDirectory` in either of
- http://wix-maven.github.io/wix-maven-plugin/lit-mojo.html
- http://wix-maven.github.io/wix-maven-plugin/light-mojo.html

**Comment by garymazz** [comment]
Got it... thanks...  closing the issue..
