### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by leif81** [wix-maven/wix-maven-plugin#11]
Once this is in Maven Central folks can start using it in their projects.

**Comment by GregDomjan** [comment]
Certainly, it's been a long time coming

**Comment by GregDomjan** [comment]
https://github.com/wix-maven/wix-maven-plugin/releases/tag/wix-maven-plugin-0.1.0
Site documentation is now up to date at http://wix-maven.github.io/wix-maven-plugin/
