### ISSUE TITLE
How to use the plugin to pass WixUIExtensions to light and / or how it can invoke WixUI_InstallDir

### ISSUE THREAD

**Issue by nigeleke** [wix-maven/wix-maven-plugin#14]
Great work on this plugin... It appears very extensive.

One feature I've been unable to determine how to use though is how to pass "-ext WixUIExtension" to light.exe.  I've assumed this may be able to be done via linkProperites, if there isn't an easier way.

Please could you let us know a) how to do that and b) if there's an easier way that the plugin can build an msi that will invoked WixUI_InstallDir...?

Much appreciated...  thanks
Nigel

**Comment by GregDomjan** [comment]
Adding a dependency of a wixext will have it included in the command line for candle/light/lit etc.

```
    <dependencies>
        <dependency>
            <groupId>${wix.groupId}</groupId>
            <artifactId>wix-toolset</artifactId>
            <version>${wix.version}</version>
            <type>wixext</type>
            <classifier>WixUIExtension</classifier>
        </dependency>
```

This integration test might show an example of what you are after.
https://github.com/wix-maven/wix-maven-plugin/tree/master/src/it/it0010-multi-module-installer
For the IT the UI is in the wixlib, and the usage of UI is in the MSI, both could be in the same project.

**Comment by nigeleke** [comment]
Thanks Greg - Problem resolved...  I /had/ been using groupId of org.wixtoolset, which, up until now, had worked for me.  Using groupId org.wixtoolset.maven resolved the extensions issue.

**Comment by madamsmall** [comment]
Can I get further guidance on this issue?
I've added this dependency to both my parent application POM, and my installer bundle POM, as well as the Bootstrap dependency for it. 
```
    <dependency>
        <groupId>org.wixtoolset.maven</groupId>
        <artifactId>wix-toolset</artifactId>
        <version>3.11.0</version>
        <type>wixext</type>
        <classifier>WixUIExtension</classifier>
    </dependency>
```

Using version 0.2.0 wix-maven-plugin, though I couldn't get 0.1.0 to work either (with UIExt 3.9.2).
Plugin pom has extensions set to true, executions listed as (id/phase) default-candle/package, default-light/package, default-smoke/package.

Product.wxs calls <UIRef Id="WixUI_Minimal" />

The build error is: 
"Error LGHT0094 Unresolved reference to symbol 'WixUI: WixUI_Minimal'

**Comment by madamsmall** [comment]
Update: I resolved this issue. The dependency call was for some reason not pulling the dlls from the repo into my .m2, but pulling them down manually and then building worked fine.

**Comment by GregDomjan** [comment]
> Update: I resolved this issue. The dependency call was for some reason not pulling the dlls from the repo into my .m2, but pulling them down manually and then building worked fine.

That is puzzling as the maven download should have pulled the file. You shouldn't have to manually populate the .m2, but I hadn't otherwise seen this issue of wix-toolset items not downloading.  

I have had issue with Nexus3 and content being blocked for NAR/NPanday - had to turn off "Validate that all content uploaded to this repository is of a MIME type appropriate for the repository format" 
Perhaps an upstream issue?
