### ISSUE TITLE
What is the current state of the project?

### ISSUE THREAD

**Issue by marker91** [wix-maven/wix-maven-plugin#15]
@GregDomjan Hi, I want to use this plugin, but the last change was 2 years ago, and it's sad, will this project be supported in the future?

**Comment by GregDomjan** [comment]
@marker91 It seems I haven't been getting notifications, sorry for the poor response.
Is there anything in particular your finding needs support/fix? 
Pull requests are good way to provide inputs.

My time towards this has been minimal for some time, looking to get a next release out soon.
Would also be happy to have additional project members.
