### ISSUE TITLE
Where is the repository for the plugin ? 

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#2]
I tried to use the plugin referencing https://oss.sonatype.org/content/repositories/snapshots . Its not in this location. Can you supply the correct location for the maven repository tag ?

**Comment by garymazz** [comment]
The repository is correct (sorry)..  I did track down the other info. 

toolset version should be: 3.7-SNAPSHOT
Plugin groupId should be: org.bitbucket.joxley
Plugin version should be either: 1.1.1,  1.1.0, 1.0.1-SNAPSHOT, 1.0.0

Please fix the documentation on github.io

**Comment by GregDomjan** [comment]
Sorry, I almost got to deploy this to central but didn't get past initial snapshot release.
Still aiming to do so.

This is not the same as the wix-maven-plugin from org.bitbucket.joxley

You could feel free to checkout and deploy your own snapshot copy in the meantime, feeling free to contribute any other suggestions.

**Comment by garymazz** [comment]
Is there an eta on the snapshot  release ?  You should place it on sonotype.org

**Comment by GregDomjan** [comment]
I've now deployed the snapshot again. 
https://oss.sonatype.org/content/repositories/snapshots/
And now also deployed a signed version.

**Comment by garymazz** [comment]
Thanks... Just used loaded it. the repository is working
