### ISSUE TITLE
msi packaging causes error  

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#3]
Line `<packaging>msi</packaging>` causes following error:

```
Scanning for projects...
[ERROR] Some problems were encountered while processing the POMs:
Unknown packaging: msi @ line 9, column 16
 @ 
The build could not read 1 project -> [Help 1]
```

Please advise

**Comment by GregDomjan** [comment]
Typically this comes from not having the plugin as an extension

In maven 2 / 3 you can mark a plugin as extension

```
      <plugin>
        <groupId>com.github.wix-maven</groupId>
        <artifactId>wix-maven-plugin</artifactId>
        <extensions>true</extensions>

```

In maven 3 there is also a new tag I haven't tried so much

```
<build>
     ...
     <extensions>
       ...
       <extension>
        <groupId>com.github.wix-maven</groupId>
        <artifactId>wix-maven-plugin</artifactId>
         <version>0.1.0-SNAPSHOT</version>
       </extension>
```

**Comment by garymazz** [comment]
Thanks for the response. 

I did have <extensions>true</extensions> set in the plugin. I'm assuming I'm not picking up the correct version/repository. 

I'm using org.bitbucket.joxley on oss.sonatype.org.

What is the url to your repository ?

**Comment by garymazz** [comment]
I just saw your other comment on issue #2  

Ok. I'll try to place is local.

**Comment by garymazz** [comment]
No change in disposition after download from sonotype.

**Comment by GregDomjan** [comment]
Since this is com.github.wix-maven and has nothing to do with org.bitbucket.joxley  this seems to be invalid. I think I commented on similar elsewhere a long time back.
