### ISSUE TITLE
Candle compiler does not execute

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#5]
There is no evidence the candle compiler is executing. 

I have also setup execute with <phase>compile</phase>  without change in behavior. 

This is my plugin code:

```
        <plugin>
            <groupId>com.github.wix-maven</groupId>
            <artifactId>wix-maven-plugin</artifactId>
            <version>0.1.0-SNAPSHOT</version>
            <configuration>
              <platforms>
                <arch>x64</arch>
              </platforms>
              <sourceFiles>
                <sourceFile>src/file1.wxs</sourceFile>
                <sourceFile>src/file2.wxs</sourceFile>
              </sourceFiles>
              <outputDirectory>build</outputDirectory>
            </configuration>
            <executions>
              <execution>
                <id>compile</id>
                <goals>
                  <goal>candle</goal>
                </goals>
              </execution>
            </executions>
        </plugin>
```

**Comment by GregDomjan** [comment]
This is not the org.bitbucket.joxley plugin.
There is no such configuration as `<sourceFiles/>`

If the `<wxsInputDirectory/>` doesn't exist, then candle step is skipped.

The idea here is convention over configuration, not having to name individual files but using a default 'includes' of "*_/_.wxs" by default.
If you want a subset using includes and excludes is what is currently supported.

I felt that wix source didn't work in the same way as the default maven java usage of sources and should not overload.  Perhaps it would have been fine.
I had the plan to expand the different types of source into multiple 'sources' but have not had the need myself.

At the moment I don't see anything to do here.

**Comment by GregDomjan** [comment]
I've spent a bit of time cleaning up and making the plugin build in Maven3.3  and realised I left some mess where I tried to expand on the usage help by stealing the npanday doc on candle/light.  Not sure if this was also contributing to confusion.
