### ISSUE TITLE
<outputFile> tag "path part" ignored

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#7]
The path part of the outputFile tag is ignored.  Setting:`<outputFile>target/file1.msi</outputFile>`  results in error:`....\target\wixobj\Release\x64 does not exist`

**Comment by GregDomjan** [comment]
Again, this is not the joxly plugin.  There is no `<outputFile/>` configuration in this plugin.

The output filename is made up from `<outputDirectory/>` , architecture, culture, `<finalName/>`and extension.

The extension based on `<packaging/>` that defaults to the `${project.packaging}`
`<outputDirectory/>` defaults to `${project.build.directory}/Release`
`<finalName/>` is the build configuration that defaults to `${project.artifactId}-${project.version}`

ie. https://github.com/wix-maven/wix-maven-plugin/blob/master/src/it/it0010-multi-module-installer/msi/pom.xml
would have outputs
- ${project.build.directory}/Release/x86/en-US/msi-0.0.1-SNAPSHOT.msi
- ${project.build.directory}/Release/x64/de-DE/msi-0.0.1-SNAPSHOT.msi
- ${project.build.directory}/Release/x86/en-US/msi-0.0.1-SNAPSHOT.msi
- ${project.build.directory}/Release/x64/de-DE/msi-0.0.1-SNAPSHOT.msi

Like visual studio, had planned to allow Release/Debug builds, but didn't need it yet myself.
