### ISSUE TITLE
<ojectFile> tag path part ignored

### ISSUE THREAD

**Issue by garymazz** [wix-maven/wix-maven-plugin#9]
When the objectFile property is set light still searches for the object files in:
`${basedir}\src\main\wix`

**Comment by GregDomjan** [comment]
This is not the org.bitbucket.joxley plugin.
There is no such configuration as `<objectFiles/>`

The configuration matching the `src\main\wix` folder is `<wxsInputDirectory/>`  and this is only used by Candle step for input *.wxs

This also relates to Issue #8  as it is using the `<intDirectory/>` path to search for all items matching `<intIncludes/>` and excluding `<intExcludes/>`
